[versions]
springBoot = "2.6.3"
logback = "1.2.10"
jupiter = "5.8.2"
abortMission = "2.8.12"
lombok = "1.18.22"
wireMock = "2.27.2"
hibernateValidator = "6.2.2.Final"
javaxEl = "3.0.0"
jackson = "2.13.1"
commonsIo = "2.11.0"
commonsLang3 = "3.12.0"
guava = "30.1-jre"
javaxInject = "1"
jetbrainsAnnotations = "20.1.0"
jsonPath = "2.7.0"
jsonSchemaValidator = "1.0.66"
markdownGenerator = "1.3.1.1"
jacoco = "0.8.2"
checkstyle = "9.2.1"

abortMissionPlugin = "2.2.2"
dockerPlugin = "0.32.0"
indexScanPlugin = "2.2.3"
lombokPlugin = "6.4.1"
springBootPlugin = "2.6.3"
gitVersionerPlugin = "1.6.7"
owaspPlugin = "6.5.3"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonPath" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchemaValidator" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
markdowngenerator = { module = "net.steppschuh.markdowngenerator:markdowngenerator", version.ref = "markdownGenerator" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
hibernate-validator = { module = "org.hibernate:hibernate-validator", version.ref = "hibernateValidator" }
javax-el-api = { module = "javax.el:javax.el-api", version.ref = "javaxEl" }
galssfish-javax-el = { module = "org.glassfish:javax.el", version.ref = "javaxEl" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
abort-mission-jupiter = { module = "com.github.nagyesta.abort-mission.boosters:abort.booster-junit-jupiter", version.ref = "abortMission" }
wiremock = { module = "com.github.tomakehurst:wiremock", version.ref = "wireMock" }

[bundles]
spring-boot = ["spring-boot-starter", "spring-boot-starter-validation"]
json = ["jackson-databind", "jackson-dataformat-yaml", "json-path", "json-schema-validator"]
logback = ["logback-classic", "logback-core"]
validation = ["hibernate-validator", "javax-el-api", "galssfish-javax-el"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBootPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
abort-mission = { id = "com.github.nagyesta.abort-mission-gradle-plugin", version.ref = "abortMissionPlugin" }
versioner = { id = "io.toolebox.git-versioner", version.ref = "gitVersionerPlugin" }
index-scan = { id = "org.sonatype.gradle.plugins.scan", version.ref = "indexScanPlugin" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owaspPlugin" }
