# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaCI-PR

on:
  push:
    branches: [ main ]
    paths:
      - 'gradle/libs.versions.toml'
      - 'gradle/verification-metadata.xml'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - 'config/ossindex/exclusions.txt'
      - '.github/workflows/gradle-ci.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'pull_request_template.md'
      - '.lift/.toml'
      - '**/.lift/.toml'
      - 'SECURITY.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/assets/**'
      - '.github/workflows/**'
      - '!.github/workflows/gradle-ci.yml'
      - '.github/pr-labeler.yml'
      - 'renovate.json'
      - '.whitesource'
      - 'gradle/libs.versions.toml'
      - 'config/ossindex/exclusions.txt'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Set up build environment
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Decode key
        run: |
          mkdir -p ${{ runner.temp }}/.gnupg/
          echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode > ${{ runner.temp }}/.gnupg/secring.gpg
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      - name: Build with Gradle
        run: >
          ./gradlew build systemTest sign
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }}
          -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          -Psigning.secretKeyRingFile=${{ runner.temp }}/.gnupg/secring.gpg
      - name: Clean-up GPG key
        if: always()
        run: |
          rm -rf ${{ runner.temp }}/.gnupg/
      - name: Upload Test reports - App
        if: always()
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: test-report-app
          path: |
            build/reports/tests/test
            build/reports/abort-mission/abort-mission-report.html
          retention-days: 5
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/report.xml
