# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaCI-PR

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Set up build environment
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2
        with:
          java-version: 11
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16 # save wrapper
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Build with Gradle
        run: ./gradlew build systemTest publishToMavenLocal
      - name: Simplify Jar name
        run: cp build/libs/yippee-ki-json-?.?.?.jar build/libs/yippee-ki-json-upload.jar
      - name: Simplify Source Jar name
        run: cp build/libs/yippee-ki-json-?.?.?-sources.jar build/libs/yippee-ki-json-upload-sources.jar
      - name: Simplify Javadoc Jar name
        run: cp build/libs/yippee-ki-json-?.?.?-javadoc.jar build/libs/yippee-ki-json-upload-javadoc.jar
      - name: Publish to Bintray
        uses: nagyesta/bintray-maven-publisher-action@v1.0.2
        with:
          DRY_RUN: "true"
          POM_FILE_NAME: "build/publications/mavenJava/pom-default.xml"
          JAR_FILE_NAME: "build/libs/yippee-ki-json-upload.jar"
          SOURCE_JAR_FILE_NAME: "build/libs/yippee-ki-json-upload-sources.jar"
          JAVADOC_JAR_FILE_NAME: "build/libs/yippee-ki-json-upload-javadoc.jar"
          ARTIFACT_GROUP_ID: "com.github.nagyesta"
          ARTIFACT_ARTIFACT_ID: "yippee-ki-json"
          ARTIFACT_VERSION: "1.0.0"
          API_USER: "nagyesta"
          API_KEY: "${{ secrets.BINTRAY_TOKEN }}"
          SUBJECT: "nagyesta"
          REPO: "sandbox"
          PACKAGE_NAME: "yippee-ki-json"
          BINTRAY_VERSION_PREFIX: "v"
          BASE_URL: "https://api.bintray.com/"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@7d5dfa54903bd909319c580a00535b483d1efcf3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/report.xml
          fail_ci_if_error: false
