# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaCI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Set up build environment
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2
        with:
          java-version: 11
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16 # save wrapper
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Build with Gradle and publish
        run: ./gradlew build systemTest tagVersion publish -PgithubToken=${{ secrets.PUBLISH_KEY }} -PgithubUser=${{ secrets.PUBLISH_USER_NAME }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@7d5dfa54903bd909319c580a00535b483d1efcf3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/report.xml
          fail_ci_if_error: false
